const LOGOS = new Set([
  "10game",
  "1pra1",
  "1xbet",
  "20bet",
  "22bet",
  "4play",
  "4win",
  "6r",
  "7games",
  "9d",
  "9f",
  "a247",
  "afun",
  "alfabet",
  "aposta1",
  "apostabet",
  "apostaganha",
  "apostamax",
  "apostaonline",
  "apostar",
  "apostatudo",
  "apostefacil",
  "apostou",
  "aviao",
  "b1bet",
  "b2xbet",
  "bandbet",
  "bateubet",
  "bcgame",
  "bet365",
  "bet4",
  "bet7k",
  "betagora",
  "betano",
  "betao",
  "betapp",
  "betbet",
  "betboo",
  "betboom",
  "betbra",
  "betbuffalo",
  "betdasorte",
  "betespecial",
  "betesporte",
  "betfair",
  "betfalcons",
  "betfast",
  "betfusion",
  "betgo",
  "betgorillas",
  "betmaster",
  "betmgm",
  "betnacional",
  "betoubet",
  "betpark",
  "betpix365",
  "betsson",
  "betsul",
  "betvip",
  "betwarrior",
  "betwinner",
  "bigbet",
  "blaze",
  "bolsadeaposta",
  "br4bet",
  "brasilbet",
  "brasildasorte",
  "brazino777",
  "brbet",
  "brx",
  "bullsbet",
  "casadeapostas",
  "cassinobet",
  "cbesportes",
  "claze",
  "dafabet",
  "donosdabola",
  "energia",
  "esporte365",
  "esportesdasorte",
  "esportivabet",
  "esportivavip",
  "estrelabet",
  "f12",
  "fanbit",
  "faz1bet",
  "fazobet",
  "fogo777",
  "fulltbet",
  "galerabet",
  "ganhei",
  "geralbet",
  "goldebet",
  "h2bet",
  "hanzbet",
  "hiperbet",
  "icebet",
  "ijogo",
  "jogajunto",
  "jogao",
  "jogodeouro",
  "jonbet",
  "kingpanda",
  "kto",
  "lancedesorte",
  "leonbet",
  "leovegas",
  "liderbet",
  "lotogreen",
  "lottoland",
  "lottu",
  "luckbet",
  "luvabet",
  "marjosports",
  "matchbook",
  "maximabet",
  "mcgames",
  "melbet",
  "meridianbet",
  "mmabet",
  "mrjackbet",
  "multibet",
  "novibet",
  "obabet",
  "onabet",
  "p9",
  "pagbet",
  "pagol",
  "papigames",
  "parimatch",
  "pinnacle",
  "pixbet",
  "playbet",
  "playpix",
  "r7",
  "recebabet",
  "reidopitaco",
  "segurobet",
  "seubet",
  "sortenabet",
  "sorteonline",
  "spinbet",
  "sportingbet",
  "sportybet",
  "stake",
  "startbet",
  "superbet",
  "supremabet",
  "tivobet",
  "ultrabet",
  "upbet",
  "uxbet",
  "vaidebet",
  "vbet",
  "verabet",
  "versus",
  "vivasorte",
  "vupibet",
  "wjcasino",
])

const SLUG_OVERRIDES: Record<string, string> = {
  betbratradeball: "betbra",
  bolsatradeball: "bolsadeaposta",
  esportiva: "esportivabet",
  f12bet: "f12",
  ganheibet: "ganhei",
  vera: "verabet",
}

function slugify(name: string) {
  return name
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .replace(/[^a-z0-9]/g, "")
}

export function bookmakerLogo(name: string) {
  const slug = slugify(name)
  const file = SLUG_OVERRIDES[slug] ?? slug
  return LOGOS.has(file) ? `/bookmakers/${file}.webp` : null
}
